config/routes.rb
Rails.application.routes.draw do
  
  get 'hotels/show' => 'searches#show', as: :show_hotel

  get 'searches/new' => 'searches#new', as: :new_search

  get 'searches/create'

  get 'searches/edit'

  get 'searches/update'

  get 'searches/destroy'

  resources :sessions 

  root 'statics#home'

  resources :users
  get 'users/index'

  get 'users/new'

  get 'users/show'

  get 'users/create'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'statics/home'

  get 'statics/about'

  get 'statics/contact'

end

app/models/remote_hotel.rb
class RemoteHotel < ActiveRecord::Base
	include HTTParty

	base_uri "http://api.ean.com/ean-services/rs/hotel/v3/list?"

	

	def self.find(destinationString, arrivalDate, departureDate)

		query = 
			    { 
			    "cid"=> "55505",
			    "minorRev"=> "99",
			    "apiKey"=> "cbrzfta369qwyrm9t5b8y8kf",
			    "locale" => "en_US", 
			    "curencyCode" => "USD",
			    "destinationString" => destinationString,
			    "arrivalDate" => arrivalDate,
			    "departureDate" => departureDate,
			    "RoomGroup" => 
			      				{ 
			                	"Room" =>
			                        {
			                        "numberOfAdults" => 2
			                        }
			                	},
			    "numberOfResults" => 20
			    }

		HTTParty.get(base_uri, query: query)
	end

end

app/models/room_avail.rb
class RoomAvail < ActiveRecord::Base
	include HTTParty

	base_uri "http://api.ean.com/ean-services/rs/hotel/v3/avail?"

		def self.find(hotelId, arrivalDate, departureDate, abc)

			query = 
			    { 
			    "cid"=> "55505",
			    "minorRev"=> "99",
			    "apiKey"=> "cbrzfta369qwyrm9t5b8y8kf",
			    "locale" => "en_US", 
			    "curencyCode" => "USD",
			    "hotelId" => hotelId,
			    "arrivalDate" => arrivalDate,
			    "departureDate" => departureDate,
			    "includeRoomImages" => true,
			    "RoomGroup" => 
			      				{ 
			                	"Room" => 
			                        [{
			                        "numberOfAdults" => 2,
			                        "numberofChildren" => 0
			                        }]
			                    	
			                	}
			    }


			HTTParty.get(base_uri, query: query)
		end

end

app/models/room_image.rb
class RoomImage < ActiveRecord::Base
		include HTTParty

		base_uri "http://api.ean.com/ean-services/rs/hotel/v3/roomImages?"

		def self.find(hotelId)
			query = 
			    { 
			    "cid"=> "55505",
			    "minorRev"=> "99",
			    "apiKey"=> "cbrzfta369qwyrm9t5b8y8kf",
			    "hotelId" => hotelId
			    }

			HTTParty.get(base_uri, query: query)
		end

end

app/models/search.rb
class Search < ActiveRecord::Base
	
end

app/models/show_remote.rb
class ShowRemote < ActiveRecord::Base
	include HTTParty

	base_uri "https://book.api.ean.com/ean-services/rs/hotel/v3/info?"

	def self.find(hotelId, options)
		query = 
				{
			    "cid"=> "55505",
			    "minorRev"=> "99",
			    "apiKey"=> "cbrzfta369qwyrm9t5b8y8kf",
			    "locale" => "en_US", 
			    "curencyCode" => "USD",
			    "hotelId" => hotelId
				}

		HTTParty.get(base_uri, query: query)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  # def index
  #   @searches = Search.paginate(:page => params[:page], :per_page => 7)
  # end
  
  def show
    response = ShowRemote.find(params[:hotelId], params[:options])
    @detail = response["HotelInformationResponse"]
    @room_responses = []
    abc = []
    
    @shovel = RoomAvail.find(params[:hotelId], params[:arrivalDate],params[:departureDate], abc)["HotelRoomAvailabilityResponse"]
    if @shovel["HotelRoomResponse"].instance_of? Hash 
      @room_responses << @shovel["HotelRoomResponse"]
    elsif @shovel["HotelRoomResponse"].instance_of? Array
      @room_responses = @shovel["HotelRoomResponse"]
    end
  

  end

  def new
    response = RemoteHotel.find(params[:destinationString], params[:arrivalDate], params[:departureDate])
    @hotels = response["HotelListResponse"]["HotelList"]["HotelSummary"]
    
    respond_to do |format|
      format.html {
        render
      }
      format.json {
        render json: @hotels
      }
     end
  end

  def create

  end


  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    # @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account successfully created."
      redirect_to :index
    else
      render :new
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to :index
    else 
      render :edit
    end
  end

  def destroy
    # @user = User.find(params[:id])
    @user.destroy
    redirect_to :index
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_stars(value)
    output = ''
    if (1..5).include?(value.floor)
      value.floor.times { output += image_tag('Star.png', :class => 'star')}
    end
    if value == (value.floor + 0.5) && value.to_i != 5
      output += image_tag('HalfStar.png', :class => 'halfstar')
    end
    output.html_safe
  end
end

  def render_pricetag(value)
    output = ''
    if value == 'true'
       output += image_tag('Tag.png', :class => 'tag')
    end
     output.html_safe
  end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/show.html.erb
<div class="vwmargin">
</div>
<div class="hotel-container">
</div>
<div class="vwmargin">
</div>
<div class="sidebar-container">
</div>
<div class="vwmargin">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Hotelpros</title>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKOn808b5c_WxU4iPBjbrH_rLqhEU_LhI&libraries=places"></script>
            <script type="text/javascript" src="http://cdn.jsdelivr.net/hammerjs/2.0.3/hammer.min.js"></script>
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
            <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
            <script type="text/javascript" src="/assets/jquery.tosrus.min.all.js"></script>
            <script type="text/javascript" src="/assets/masonry.pkgd.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.1/masonry.pkgd.min.js"></script>
            <link href='https://fonts.googleapis.com/css?family=Lato:400,700,700italic,900italic' rel='stylesheet' type='text/css'>
            <link href='http://fonts.googleapis.com/css?family=Raleway:400,800,500,300,200' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
            <link href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/css/bootstrap-datepicker.min.css' rel='stylesheet' type='text/css'>
            <link href="assets/custom.scss" rel="stylesheet" type="text/css">
            <link rel="stylesheet" type="text/css" href="/assets/jquery.tosrus.all.scss" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

<body>

<!-- beginning of the navbar, adds fixed to top to stick to top of page, inverse for dark color, and container fluid for full viewport -->
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
    <!-- adds button with icon bars for collapse on smaller screens -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <!-- <a class="navbar-brand" href="#" id="booker-logo">Booker Pro</a> -->
      <%= link_to "BOOKER PRO", root_path, :id => "booker-logo", :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
    
        <li class="dropdown">
          <a class="dropdown-toggle active" data-toggle="dropdown" href="#">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Sign Up</a></li>
            <li><a href="#">Login</a></li>
          </ul>
        </li>
        <li><a href="#">My Trips</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>


<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/searches/_choose_room.html.erb
<script>
$( document ).ready(function() {
  $('select').bind('change', function () {
      var val = parseInt($(this).val(), 10) + 1,
          str = '';

      for (var i=1; i<val;i++) {
          str += '<div class="rooms-selector-container" name="adultinput' + i + ']">Adults<br><select class="form-control"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option></select></div><div class="rooms-selector-container" name="childreninput' + i + '">Children<br><select class="form-control"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option></select></div><br>'
      }

      $('#container').html(str);
  });
});
</script>

<%= form_tag show_hotel_path, method: :get do %>

  

  <div class="check-in-container">
  Check In<br>
    <%= text_field_tag :arrivalDate, params[:arrivalDate], placeholder: 'MM/DD/YY', :data => {:provide => "datepicker"}, :class => 'search-container' %>
  </div>

  <div class="check-out-container">

  Check Out<br>

    <%= text_field_tag :departureDate, params[:departureDate], placeholder: 'MM/DD/YY', :data => {:provide => "datepicker"}, :class => 'search-container'  %>
  </div>
  <div class="hotelId">
    <%= text_field_tag :hotelId, @shovel["hotelId"], :class => 'search-container hotelId' %>
  </div>


  <div class="rooms-selector-container">
    Rooms<br>
    <select class="form-control">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>

    </select>
  </div>

  <div class="rooms-selector-container">
    Adults<br>
    <select class="form-control"  >
      <option value="0">0</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>

    </select>
  </div>
  <div class="rooms-selector-container">
    Children<br>
    <select class="form-control">
      <option value="0">0</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>

    </select>
  </div>

    <div class="update-button-container">
    <%= submit_tag "Update",  :class => 'search-container btn-small' %>
    </div><br>
  <div id="container">
  </div>
<% end %>
    

app/views/searches/_filter.html.erb
<body onload="initialize()">
<section class="searchpartial text-center">
  <%= form_tag new_search_path, method: :get do %>
  	<div id="locationField">
        <%= text_field_tag :destinationString, nil, placeholder: 'Destination', :id => 'autocomplete', :onFocus => 'geolocate()', :class => 'search-container' %>
    </div>
    <hr>
	    <%= text_field_tag :arrivalDate, params[:arrivalDate], placeholder: 'Check In', :data => {:provide => "datepicker"}, :class => 'search-container datepicker'  %>
	    <%#= text_field_tag :arrivalDate, nil, placeholder: 'Check In', :data => {:provide => "datepicker"}, :class => 'search-container datepicker'  %>

	    <%= text_field_tag :departureDate, params[:departureDate], placeholder: 'Check Out', :data => {:provide => "datepicker"}, :class => 'search-container datepicker'  %>

      <div class="dropdown guests-dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          1 Guest
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="#">2 Guests</a></li>
          <li><a href="#">3 Guests</a></li>
          <li><a href="#">4 Guests</a></li>
          <li><a href="#">5 Guests</a></li>
        </ul>
      </div>
      <hr>
      Price Range <b>$0</b> <input id="ex2" type="text" class="span2" value="" data-slider-min="0" data-slider-max="700" data-slider-step="1" data-slider-value="[50,500]"/> <b>$700</b>
  	<% end %>
    <hr>
</section>
</body>

<script>
var slider = new Slider('#ex2', {});
function initialize() {
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {HTMLInputElement} */(document.getElementById('autocomplete')));
}
</script>

app/views/searches/_rooms.html.erb
<% @room_responses.each do |room_response|%>
	<% @detail["RoomTypes"]["RoomType"].each do |room_detail| %> 
		<% if room_response["roomTypeCode"].to_s == room_detail["@roomCode"].to_s && room_response["RoomImages"] != nil %>
			
			<div class="individual-room-container">
				<%= image_tag (room_response["RoomImages"]["RoomImage"].first[1].to_s[0...-5] + "b.jpg"), :class => "room-image" %>
				<div class="price-box">
					<div class="hotel-rate price-info">
						<%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageRate"]) %>
						<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Array %>
							<%= render_pricetag(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"][0]["@promo"]) %>
						<% elsif room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Hash %>
							<%= render_pricetag(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"]["@promo"]) %>										
						<% end %>
					</div>
				</div>

				<div class="description-price-container">
					<div class="room-description">
						<%= room_response["roomTypeDescription"] %>
						<br>
					</div>
					<div class="price-with-promo">
						<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Array %>
							<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"][0]["@promo"] == "true" %>
								<del><%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageBaseRate"]) %></del>
							<% end %>
						<% elsif room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Hash %>
								<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"]["@promo"] == "true" %>
									<del><%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageBaseRate"]) %></del>
								<% end %>
						<% end %>
							<%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageRate"]) %>
					</div>
				</div>		

					<% if room_response["BedTypes"] %>
						<% if room_response["BedTypes"]["BedType"].instance_of? Array %>
							<% room_response["BedTypes"]["BedType"].each do |bed| %>
								<div class="bedtypes">
									<div class="bed-description">
										<%= bed["description"] %>
									</div>
									<div class="book-now">
										<%= button_tag 'BOOK NOW', :class => 'search-container' %>
									</div>
								</div>
							<% end %>
						<% else %>
							<div class="bedtypes">
								<div class="bed-description">
									<%= room_response["BedTypes"]["BedType"]["description"] %>
								</div>
								<div class="book-now">
									<%= button_tag 'BOOK NOW', :class => 'search-container' %>
								</div>
							</div>
						<% end %>
					<% end %>
			</div>

				<% elsif room_response["roomTypeCode"].to_s == room_detail["@roomCode"].to_s && room_response["RoomImages"] == nil %>
			<div class="individual-room-container">
				<%= image_tag  (@detail["HotelImages"]["HotelImage"][0]["url"]), :class => "room-image"%>
				<div class="price-box">
					<div class="hotel-rate price-info">
						<%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageRate"]) %>
						<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Array %>
							<%= render_pricetag(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"][0]["@promo"]) %>
						<% elsif room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Hash %>
							<%= render_pricetag(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"]["@promo"]) %>										
						<% end %>
					</div>
				</div>

				<div class="description-price-container">
					<div class="room-description">
						<%= room_response["roomTypeDescription"] %>
						<br>
					</div>
					<div class="price-with-promo">
						<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Array %>
							<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"][0]["@promo"] == "true" %>
								<del><%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageBaseRate"]) %></del>
							<% end %>
						<% elsif room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"].instance_of? Hash %>
								<% if room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["NightlyRatesPerRoom"]["NightlyRate"]["@promo"] == "true" %>
									<del><%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageBaseRate"]) %></del>
								<% end %>
						<% end %>
							<%= number_to_currency(room_response["RateInfos"]["RateInfo"]["ChargeableRateInfo"]["@averageRate"]) %>
					</div>
				</div>		

					<% if room_response["BedTypes"] %>
						<% if room_response["BedTypes"]["BedType"].instance_of? Array %>
							<% room_response["BedTypes"]["BedType"].each do |bed| %>
							<div class="bedtypes">
								<div class="bed-description">
									<%= bed["description"] %>
								</div>
								<div class="book-now">
										<%= button_tag 'BOOK NOW', :class => 'search-container' %>
								</div>
							</div>
							<% end %>
						<% else %>
							<div class="bedtypes">
								<div class="bed-description">
									<%= room_response["BedTypes"]["BedType"]["description"] %>
								</div>
								<div class="book-now">
									<%= button_tag 'BOOK NOW', :class => 'search-container' %>
								</div>
							</div>
						<% end %>
					<% end %>
			</div>
		<% end %>
	<% end %>	
<% end %>

app/views/searches/_search_min.html.erb
<div class="hotel-wrapper">
	<div class="search-box">
	    <%= render 'filter' %>
	</div>
<% @hotels.each do |hotel| %>
    <div class="all-hotels">
    	<div class="grow">
	        <%= link_to show_hotel_path(:hotelId => hotel["hotelId"]), :class => "link-underline clearfix"	 do %>
	            <img src="http://media.expedia.com<%= hotel["thumbNailUrl"][0...-5] + "b.jpg" %>" />
	            <div class="price-box"><div id="booker-logo" class="hotel-rate price-info">$<%= hotel["lowRate"].round(0) %></div></div>
	    </div>
            <div class="hotel-name" id="booker-logo"><%= hotel["name"] %></div>
            <span class="hotel-rating" id="booker-logo"><%= hotel["hotelRating"] %> star hotel | </span>
            <span class="book-now" id="booker-logo"><%= link_to "Book Now",show_hotel_path(:hotelId => hotel["hotelId"]) %></span>
        <% end %>
    </div>
<% end %>
</div>

<div class="map-wrapper">
	<div id="google-map"></div>
</div>

app/views/searches/_search_result.html.erb
<div id="all-content">

	<div class="hotel-wrapper" id="map-padding">

		<div class="search-box">
			<%= render 'filter' %>
		</div>

		<% @hotels.each do |hotel| %>


			<div id="booker-logo" class="all-hotels">

				<div class="grow">

					<%= link_to show_hotel_path(:hotelId => hotel["hotelId"],:arrivalDate => params[:arrivalDate], :departureDate => params[:departureDate]),:class => "link-underline clearfix" do %>

						<div class="results-image">

							<div class="results-image-inner">

								<img src="http://media.expedia.com<%= hotel["thumbNailUrl"][0...-5] + "b.jpg" %>" />

								<div class="price-box">
									<div class="hotel-rate price-info">$<%= hotel["lowRate"].round(0) %></div>
								</div>
								<div class="lower-info">
									<div class="hotel-name"><%= hotel["name"].gsub(/&amp;/, '&')  %></div>

									<span class="hotel-rating"><%= hotel["hotelRating"] %> star hotel |</span>
									<span><%= link_to " Book Now",show_hotel_path(:hotelId => hotel["hotelId"],:arrivalDate =>"08/18/15", :departureDate => "08/19/15"), :class => "book-now" %></span>

								</div>

							</div>

						</div>

					<% end %>

				</div>
				
			</div>

		<% end %>

		<%#= will_paginate @searches %>

	</div>

	<div class="map-wrapper">
		<div id="google-map"></div>
	</div>

</div>

app/views/searches/create.html.erb
<%= render 'sidebar' %>

app/views/searches/destroy.html.erb
<h1>Searches#destroy</h1>
<p>Find me in app/views/searches/destroy.html.erb</p>

app/views/searches/edit.html.erb
<br><br><br><br><br><br><br><br><br><br><br>

<%= render 'filter' %>

app/views/searches/new.html.erb
<!-- <div class="search-render"> -->
    <%#= render "searches/search_result" %>
<!-- </div> -->
		<!--  for big screens -->

		<div class="big-view">
			<div>
				<%= render "searches/search_result" %>
			</div>
	    </div>
		<!--  for a smaller screen -->


		<!-- <div class="small-view">
			<div> -->
				<%#= render "searches/search_min" %>
			<!-- </div>
	    </div> -->
		<!-- <div class="small-view">
		    	<div class="col-md-7 filter-container"> -->
					<%#= render 'filter' %>
				<!-- </div>

		        <div id="search-padding" class="row">
					<div class="col-md-7 relative-column"> -->
						<%#= render "searches/search_min" %>
					<!-- </div>
				<div class="map-wrapper">
					<div id="google-map" class="col-md-5"></div>
				</div>
			</div>
		 </div>
 -->
	



<%#= @hotels %>
<%#= @hotels.inspect %>

	

app/views/searches/update.html.erb
<h1>Searches#update</h1>
<p>Find me in app/views/searches/update.html.erb</p>

app/views/statics/_search.html.erb
<body onload="initialize()">
<section class="searchpartial text-center">
  <%= form_tag new_search_path, method: :get do %>
  	<div id="locationField">
        <%= text_field_tag :destinationString, nil, placeholder: 'Where do you want to go?', :id => 'autocomplete', :onFocus => 'geolocate()', :class => 'search-container destination' %>
    </div>

	    <%= text_field_tag :arrivalDate, nil, placeholder: 'Check In', :data => {:provide => "datepicker"}, :class => 'search-container datepicker'  %>
	    <%= text_field_tag :departureDate, nil, placeholder: 'Check Out', :data => {:provide => "datepicker"}, :class => 'search-container datepicker'  %>
	    <%= submit_tag "Search", :class => 'submit-button search-container' %>

  	<% end %>
</section>
</body>

<script>
function initialize() {
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {HTMLInputElement} */(document.getElementById('autocomplete')));
}
</script>

  

app/views/statics/about.html.erb
<%= render 'search' %>

app/views/statics/contact.html.erb
<h1>Statics#contact</h1>
<p>Find me in app/views/statics/contact.html.erb</p>

app/views/statics/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Booker Pro</title>
		<link href='http://fonts.googleapis.com/css?family=Lato:100,200,300,400,700,700italic,900italic' rel='stylesheet' type='text/css'>
	</head>

<body id="booker-logo">

	<div id="homepage-photo">

		<div class='title'>

			<h1 class="homepage-title" style="font-family: 'Lato', sans-serif; font-weight: 900; font-style: normal;">Seamless Hotel Bookings</h1>

			<h2 class="homepage-title" style="font-family: 'Lato', sans-serif; font-weight: 400; font-style: normal;">We Make Travel Easy</h2>

		</div>

	</div>

	<div id="homepage-float" "text-center">

		<%= render 'search' %>

	</div>


</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>